### ISSUE TITLE
protocol must be quoted in error strings

### ISSUE THREAD

**Issue by RizzerOnGitHub** [koofr/go-httpclient#2]
Running tests for go-httpclient triggers errors:

        /build/1st/golang-github-koofr-go-httpclient-0.0~git20190818.e0dc8fd/obj-x86_64-linux-gnu/src/github.com/koofr/go-httpclient/httpclient_test.go:42
          New
          /build/1st/golang-github-koofr-go-httpclient-0.0~git20190818.e0dc8fd/obj-x86_64-linux-gnu/src/github.com/koofr/go-httpclient/httpclient_test.go:66
            should get error if FullURL is invalid [It]
            /build/1st/golang-github-koofr-go-httpclient-0.0~git20190818.e0dc8fd/obj-x86_64-linux-gnu/src/github.com/koofr/go-httpclient/httpclient_test.go:103
        
            Expected
                <string>: parse \"://???\": missing protocol scheme
            to equal
                <string>: parse ://???: missing protocol scheme

Apparently the protocol strings need to be quoted. This patch fixes the error:

    --- a/httpclient_test.go
    +++ b/httpclient_test.go
    @@ -106,7 +106,7 @@
                                    FullURL: "://???",
                            })
                            Expect(err).To(HaveOccurred())
    -                       Expect(err.Error()).To(Equal(`parse ://???: missing protocol scheme`))
    +                       Expect(err.Error()).To(Equal(`parse "://???": missing protocol scheme`))
                    })
            })
    
    @@ -905,7 +905,7 @@
    
                            _, err = client.Request(req)
                            Expect(err).To(HaveOccurred())
    -                       Expect(err.Error()).To(Equal("Post http:/: broken body"))
    +                       Expect(err.Error()).To(Equal("Post \"http:/\": broken body"))
    
                            <-waitCh
                    })

This is evidently a change in behaviour in Go 1.14. The tests passed fine in Go 1.13.

**Comment by bancek** [comment]
I think it would be better to just check that the error `Contains("missing protocol scheme")` and `Contains("broken body")`.

Can you please open a pull request with a fix that will work for both Go 1.14 and Go 1.13?

**Comment by RizzerOnGitHub** [comment]
I'm not sufficiently fluent in Go to cover both 1.13 and 1.14 efficiently.  Using Contains sounds like a good idea.

**Comment by bancek** [comment]
Thank you for your report.
